//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_06.WebSrv {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://el.pcz.pl/", ConfigurationName="WebSrv.SelectSoap")]
    public interface SelectSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/Devices", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Devices();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/Devices", ReplyAction="*")]
        System.Threading.Tasks.Task DevicesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/OnlinesObises", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void OnlinesObises(int DeviceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/OnlinesObises", ReplyAction="*")]
        System.Threading.Tasks.Task OnlinesObisesAsync(int DeviceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/OnlinesFromTo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void OnlinesFromTo(int DeviceID, System.DateTime dtFrom, System.DateTime dtTo, string ObisCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/OnlinesFromTo", ReplyAction="*")]
        System.Threading.Tasks.Task OnlinesFromToAsync(int DeviceID, System.DateTime dtFrom, System.DateTime dtTo, string ObisCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/OnlinesLastN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void OnlinesLastN(int DeviceID, int LastN, string ObisCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/OnlinesLastN", ReplyAction="*")]
        System.Threading.Tasks.Task OnlinesLastNAsync(int DeviceID, int LastN, string ObisCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/ProfilesObises", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ProfilesObises(int DeviceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/ProfilesObises", ReplyAction="*")]
        System.Threading.Tasks.Task ProfilesObisesAsync(int DeviceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/ProfilesFromTo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ProfilesFromTo(int DeviceID, System.DateTime dtFrom, System.DateTime dtTo, string ObisCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/ProfilesFromTo", ReplyAction="*")]
        System.Threading.Tasks.Task ProfilesFromToAsync(int DeviceID, System.DateTime dtFrom, System.DateTime dtTo, string ObisCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/ProfilesLastN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ProfilesLastN(int DeviceID, int LastN, string ObisCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/ProfilesLastN", ReplyAction="*")]
        System.Threading.Tasks.Task ProfilesLastNAsync(int DeviceID, int LastN, string ObisCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/MeasurePoints", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void MeasurePoints();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/MeasurePoints", ReplyAction="*")]
        System.Threading.Tasks.Task MeasurePointsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/OnlinesFrom", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void OnlinesFrom(int DeviceID, System.DateTime dtFrom, string ObisCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/OnlinesFrom", ReplyAction="*")]
        System.Threading.Tasks.Task OnlinesFromAsync(int DeviceID, System.DateTime dtFrom, string ObisCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/ProfilesFrom", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ProfilesFrom(int DeviceID, System.DateTime dtFrom, string ObisCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/ProfilesFrom", ReplyAction="*")]
        System.Threading.Tasks.Task ProfilesFromAsync(int DeviceID, System.DateTime dtFrom, string ObisCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/XmlDevices", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable XmlDevices();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/XmlDevices", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> XmlDevicesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/XmlOnlinesObises", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable XmlOnlinesObises(int DeviceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/XmlOnlinesObises", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> XmlOnlinesObisesAsync(int DeviceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/XmlOnlinesFromTo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable XmlOnlinesFromTo(int DeviceID, System.DateTime dtFrom, System.DateTime dtTo, string ObisCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/XmlOnlinesFromTo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> XmlOnlinesFromToAsync(int DeviceID, System.DateTime dtFrom, System.DateTime dtTo, string ObisCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/XmlOnlinesLastN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable XmlOnlinesLastN(int DeviceID, int LastN, string ObisCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/XmlOnlinesLastN", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> XmlOnlinesLastNAsync(int DeviceID, int LastN, string ObisCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/XmlProfilesObises", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable XmlProfilesObises(int DeviceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/XmlProfilesObises", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> XmlProfilesObisesAsync(int DeviceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/XmlProfilesFromTo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable XmlProfilesFromTo(int DeviceID, System.DateTime dtFrom, System.DateTime dtTo, string ObisCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/XmlProfilesFromTo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> XmlProfilesFromToAsync(int DeviceID, System.DateTime dtFrom, System.DateTime dtTo, string ObisCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/XmlProfilesLastN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable XmlProfilesLastN(int DeviceID, int LastN, string ObisCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/XmlProfilesLastN", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> XmlProfilesLastNAsync(int DeviceID, int LastN, string ObisCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/XmlMeasurePoints", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable XmlMeasurePoints();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/XmlMeasurePoints", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> XmlMeasurePointsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/XmlOnlinesFrom", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable XmlOnlinesFrom(int DeviceID, System.DateTime dtFrom, string ObisCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/XmlOnlinesFrom", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> XmlOnlinesFromAsync(int DeviceID, System.DateTime dtFrom, string ObisCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/XmlProfilesFrom", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable XmlProfilesFrom(int DeviceID, System.DateTime dtFrom, string ObisCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://el.pcz.pl/XmlProfilesFrom", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> XmlProfilesFromAsync(int DeviceID, System.DateTime dtFrom, string ObisCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SelectSoapChannel : Lab_06.WebSrv.SelectSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SelectSoapClient : System.ServiceModel.ClientBase<Lab_06.WebSrv.SelectSoap>, Lab_06.WebSrv.SelectSoap {
        
        public SelectSoapClient() {
        }
        
        public SelectSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SelectSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SelectSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SelectSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Devices() {
            base.Channel.Devices();
        }
        
        public System.Threading.Tasks.Task DevicesAsync() {
            return base.Channel.DevicesAsync();
        }
        
        public void OnlinesObises(int DeviceID) {
            base.Channel.OnlinesObises(DeviceID);
        }
        
        public System.Threading.Tasks.Task OnlinesObisesAsync(int DeviceID) {
            return base.Channel.OnlinesObisesAsync(DeviceID);
        }
        
        public void OnlinesFromTo(int DeviceID, System.DateTime dtFrom, System.DateTime dtTo, string ObisCode) {
            base.Channel.OnlinesFromTo(DeviceID, dtFrom, dtTo, ObisCode);
        }
        
        public System.Threading.Tasks.Task OnlinesFromToAsync(int DeviceID, System.DateTime dtFrom, System.DateTime dtTo, string ObisCode) {
            return base.Channel.OnlinesFromToAsync(DeviceID, dtFrom, dtTo, ObisCode);
        }
        
        public void OnlinesLastN(int DeviceID, int LastN, string ObisCode) {
            base.Channel.OnlinesLastN(DeviceID, LastN, ObisCode);
        }
        
        public System.Threading.Tasks.Task OnlinesLastNAsync(int DeviceID, int LastN, string ObisCode) {
            return base.Channel.OnlinesLastNAsync(DeviceID, LastN, ObisCode);
        }
        
        public void ProfilesObises(int DeviceID) {
            base.Channel.ProfilesObises(DeviceID);
        }
        
        public System.Threading.Tasks.Task ProfilesObisesAsync(int DeviceID) {
            return base.Channel.ProfilesObisesAsync(DeviceID);
        }
        
        public void ProfilesFromTo(int DeviceID, System.DateTime dtFrom, System.DateTime dtTo, string ObisCode) {
            base.Channel.ProfilesFromTo(DeviceID, dtFrom, dtTo, ObisCode);
        }
        
        public System.Threading.Tasks.Task ProfilesFromToAsync(int DeviceID, System.DateTime dtFrom, System.DateTime dtTo, string ObisCode) {
            return base.Channel.ProfilesFromToAsync(DeviceID, dtFrom, dtTo, ObisCode);
        }
        
        public void ProfilesLastN(int DeviceID, int LastN, string ObisCode) {
            base.Channel.ProfilesLastN(DeviceID, LastN, ObisCode);
        }
        
        public System.Threading.Tasks.Task ProfilesLastNAsync(int DeviceID, int LastN, string ObisCode) {
            return base.Channel.ProfilesLastNAsync(DeviceID, LastN, ObisCode);
        }
        
        public void MeasurePoints() {
            base.Channel.MeasurePoints();
        }
        
        public System.Threading.Tasks.Task MeasurePointsAsync() {
            return base.Channel.MeasurePointsAsync();
        }
        
        public void OnlinesFrom(int DeviceID, System.DateTime dtFrom, string ObisCode) {
            base.Channel.OnlinesFrom(DeviceID, dtFrom, ObisCode);
        }
        
        public System.Threading.Tasks.Task OnlinesFromAsync(int DeviceID, System.DateTime dtFrom, string ObisCode) {
            return base.Channel.OnlinesFromAsync(DeviceID, dtFrom, ObisCode);
        }
        
        public void ProfilesFrom(int DeviceID, System.DateTime dtFrom, string ObisCode) {
            base.Channel.ProfilesFrom(DeviceID, dtFrom, ObisCode);
        }
        
        public System.Threading.Tasks.Task ProfilesFromAsync(int DeviceID, System.DateTime dtFrom, string ObisCode) {
            return base.Channel.ProfilesFromAsync(DeviceID, dtFrom, ObisCode);
        }
        
        public System.Data.DataTable XmlDevices() {
            return base.Channel.XmlDevices();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> XmlDevicesAsync() {
            return base.Channel.XmlDevicesAsync();
        }
        
        public System.Data.DataTable XmlOnlinesObises(int DeviceID) {
            return base.Channel.XmlOnlinesObises(DeviceID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> XmlOnlinesObisesAsync(int DeviceID) {
            return base.Channel.XmlOnlinesObisesAsync(DeviceID);
        }
        
        public System.Data.DataTable XmlOnlinesFromTo(int DeviceID, System.DateTime dtFrom, System.DateTime dtTo, string ObisCode) {
            return base.Channel.XmlOnlinesFromTo(DeviceID, dtFrom, dtTo, ObisCode);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> XmlOnlinesFromToAsync(int DeviceID, System.DateTime dtFrom, System.DateTime dtTo, string ObisCode) {
            return base.Channel.XmlOnlinesFromToAsync(DeviceID, dtFrom, dtTo, ObisCode);
        }
        
        public System.Data.DataTable XmlOnlinesLastN(int DeviceID, int LastN, string ObisCode) {
            return base.Channel.XmlOnlinesLastN(DeviceID, LastN, ObisCode);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> XmlOnlinesLastNAsync(int DeviceID, int LastN, string ObisCode) {
            return base.Channel.XmlOnlinesLastNAsync(DeviceID, LastN, ObisCode);
        }
        
        public System.Data.DataTable XmlProfilesObises(int DeviceID) {
            return base.Channel.XmlProfilesObises(DeviceID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> XmlProfilesObisesAsync(int DeviceID) {
            return base.Channel.XmlProfilesObisesAsync(DeviceID);
        }
        
        public System.Data.DataTable XmlProfilesFromTo(int DeviceID, System.DateTime dtFrom, System.DateTime dtTo, string ObisCode) {
            return base.Channel.XmlProfilesFromTo(DeviceID, dtFrom, dtTo, ObisCode);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> XmlProfilesFromToAsync(int DeviceID, System.DateTime dtFrom, System.DateTime dtTo, string ObisCode) {
            return base.Channel.XmlProfilesFromToAsync(DeviceID, dtFrom, dtTo, ObisCode);
        }
        
        public System.Data.DataTable XmlProfilesLastN(int DeviceID, int LastN, string ObisCode) {
            return base.Channel.XmlProfilesLastN(DeviceID, LastN, ObisCode);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> XmlProfilesLastNAsync(int DeviceID, int LastN, string ObisCode) {
            return base.Channel.XmlProfilesLastNAsync(DeviceID, LastN, ObisCode);
        }
        
        public System.Data.DataTable XmlMeasurePoints() {
            return base.Channel.XmlMeasurePoints();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> XmlMeasurePointsAsync() {
            return base.Channel.XmlMeasurePointsAsync();
        }
        
        public System.Data.DataTable XmlOnlinesFrom(int DeviceID, System.DateTime dtFrom, string ObisCode) {
            return base.Channel.XmlOnlinesFrom(DeviceID, dtFrom, ObisCode);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> XmlOnlinesFromAsync(int DeviceID, System.DateTime dtFrom, string ObisCode) {
            return base.Channel.XmlOnlinesFromAsync(DeviceID, dtFrom, ObisCode);
        }
        
        public System.Data.DataTable XmlProfilesFrom(int DeviceID, System.DateTime dtFrom, string ObisCode) {
            return base.Channel.XmlProfilesFrom(DeviceID, dtFrom, ObisCode);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> XmlProfilesFromAsync(int DeviceID, System.DateTime dtFrom, string ObisCode) {
            return base.Channel.XmlProfilesFromAsync(DeviceID, dtFrom, ObisCode);
        }
    }
}
