//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _08_B_WebServiceClient.MyWebServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfDouble", Namespace="http://tempuri.org/", ItemName="double")]
    [System.SerializableAttribute()]
    public class ArrayOfDouble : System.Collections.Generic.List<double> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultClass", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResultClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private _08_B_WebServiceClient.MyWebServiceReference.ArrayOfString LstStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private _08_B_WebServiceClient.MyWebServiceReference.MyBmp BmpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private _08_B_WebServiceClient.MyWebServiceReference.MyDict DictField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public _08_B_WebServiceClient.MyWebServiceReference.ArrayOfString LstStr {
            get {
                return this.LstStrField;
            }
            set {
                if ((object.ReferenceEquals(this.LstStrField, value) != true)) {
                    this.LstStrField = value;
                    this.RaisePropertyChanged("LstStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public _08_B_WebServiceClient.MyWebServiceReference.MyBmp Bmp {
            get {
                return this.BmpField;
            }
            set {
                if ((object.ReferenceEquals(this.BmpField, value) != true)) {
                    this.BmpField = value;
                    this.RaisePropertyChanged("Bmp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public _08_B_WebServiceClient.MyWebServiceReference.MyDict Dict {
            get {
                return this.DictField;
            }
            set {
                if ((object.ReferenceEquals(this.DictField, value) != true)) {
                    this.DictField = value;
                    this.RaisePropertyChanged("Dict");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyBmp", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MyBmp : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BmpAsBase64Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BmpExtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BmpAsBase64 {
            get {
                return this.BmpAsBase64Field;
            }
            set {
                if ((object.ReferenceEquals(this.BmpAsBase64Field, value) != true)) {
                    this.BmpAsBase64Field = value;
                    this.RaisePropertyChanged("BmpAsBase64");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BmpExt {
            get {
                return this.BmpExtField;
            }
            set {
                if ((object.ReferenceEquals(this.BmpExtField, value) != true)) {
                    this.BmpExtField = value;
                    this.RaisePropertyChanged("BmpExt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyDict", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MyDict : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private _08_B_WebServiceClient.MyWebServiceReference.ArrayOfString KeysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private _08_B_WebServiceClient.MyWebServiceReference.ArrayOfInt ValuesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public _08_B_WebServiceClient.MyWebServiceReference.ArrayOfString Keys {
            get {
                return this.KeysField;
            }
            set {
                if ((object.ReferenceEquals(this.KeysField, value) != true)) {
                    this.KeysField = value;
                    this.RaisePropertyChanged("Keys");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public _08_B_WebServiceClient.MyWebServiceReference.ArrayOfInt Values {
            get {
                return this.ValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.ValuesField, value) != true)) {
                    this.ValuesField = value;
                    this.RaisePropertyChanged("Values");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataClass", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DataClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int LenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BmpTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BytesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Len {
            get {
                return this.LenField;
            }
            set {
                if ((this.LenField.Equals(value) != true)) {
                    this.LenField = value;
                    this.RaisePropertyChanged("Len");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BmpType {
            get {
                return this.BmpTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.BmpTypeField, value) != true)) {
                    this.BmpTypeField = value;
                    this.RaisePropertyChanged("BmpType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] Bytes {
            get {
                return this.BytesField;
            }
            set {
                if ((object.ReferenceEquals(this.BytesField, value) != true)) {
                    this.BytesField = value;
                    this.RaisePropertyChanged("Bytes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyWebServiceReference.MyWebServiceSoap")]
    public interface MyWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        _08_B_WebServiceClient.MyWebServiceReference.HelloWorldResponse HelloWorld(_08_B_WebServiceClient.MyWebServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<_08_B_WebServiceClient.MyWebServiceReference.HelloWorldResponse> HelloWorldAsync(_08_B_WebServiceClient.MyWebServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld2", ReplyAction="*")]
        _08_B_WebServiceClient.MyWebServiceReference.HelloWorld2Response HelloWorld2(_08_B_WebServiceClient.MyWebServiceReference.HelloWorld2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld2", ReplyAction="*")]
        System.Threading.Tasks.Task<_08_B_WebServiceClient.MyWebServiceReference.HelloWorld2Response> HelloWorld2Async(_08_B_WebServiceClient.MyWebServiceReference.HelloWorld2Request request);
        
        // CODEGEN: Generating message contract since element name GetRandomArrayResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRandomArray", ReplyAction="*")]
        _08_B_WebServiceClient.MyWebServiceReference.GetRandomArrayResponse GetRandomArray(_08_B_WebServiceClient.MyWebServiceReference.GetRandomArrayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRandomArray", ReplyAction="*")]
        System.Threading.Tasks.Task<_08_B_WebServiceClient.MyWebServiceReference.GetRandomArrayResponse> GetRandomArrayAsync(_08_B_WebServiceClient.MyWebServiceReference.GetRandomArrayRequest request);
        
        // CODEGEN: Generating message contract since element name GetResultResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetResult", ReplyAction="*")]
        _08_B_WebServiceClient.MyWebServiceReference.GetResultResponse GetResult(_08_B_WebServiceClient.MyWebServiceReference.GetResultRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetResult", ReplyAction="*")]
        System.Threading.Tasks.Task<_08_B_WebServiceClient.MyWebServiceReference.GetResultResponse> GetResultAsync(_08_B_WebServiceClient.MyWebServiceReference.GetResultRequest request);
        
        // CODEGEN: Generating message contract since element name data from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetResult2", ReplyAction="*")]
        _08_B_WebServiceClient.MyWebServiceReference.GetResult2Response GetResult2(_08_B_WebServiceClient.MyWebServiceReference.GetResult2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetResult2", ReplyAction="*")]
        System.Threading.Tasks.Task<_08_B_WebServiceClient.MyWebServiceReference.GetResult2Response> GetResult2Async(_08_B_WebServiceClient.MyWebServiceReference.GetResult2Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public _08_B_WebServiceClient.MyWebServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(_08_B_WebServiceClient.MyWebServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public _08_B_WebServiceClient.MyWebServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(_08_B_WebServiceClient.MyWebServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorld2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld2", Namespace="http://tempuri.org/", Order=0)]
        public _08_B_WebServiceClient.MyWebServiceReference.HelloWorld2RequestBody Body;
        
        public HelloWorld2Request() {
        }
        
        public HelloWorld2Request(_08_B_WebServiceClient.MyWebServiceReference.HelloWorld2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorld2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public HelloWorld2RequestBody() {
        }
        
        public HelloWorld2RequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorld2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld2Response", Namespace="http://tempuri.org/", Order=0)]
        public _08_B_WebServiceClient.MyWebServiceReference.HelloWorld2ResponseBody Body;
        
        public HelloWorld2Response() {
        }
        
        public HelloWorld2Response(_08_B_WebServiceClient.MyWebServiceReference.HelloWorld2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorld2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorld2Result;
        
        public HelloWorld2ResponseBody() {
        }
        
        public HelloWorld2ResponseBody(string HelloWorld2Result) {
            this.HelloWorld2Result = HelloWorld2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRandomArrayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRandomArray", Namespace="http://tempuri.org/", Order=0)]
        public _08_B_WebServiceClient.MyWebServiceReference.GetRandomArrayRequestBody Body;
        
        public GetRandomArrayRequest() {
        }
        
        public GetRandomArrayRequest(_08_B_WebServiceClient.MyWebServiceReference.GetRandomArrayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRandomArrayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int n;
        
        public GetRandomArrayRequestBody() {
        }
        
        public GetRandomArrayRequestBody(int n) {
            this.n = n;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRandomArrayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRandomArrayResponse", Namespace="http://tempuri.org/", Order=0)]
        public _08_B_WebServiceClient.MyWebServiceReference.GetRandomArrayResponseBody Body;
        
        public GetRandomArrayResponse() {
        }
        
        public GetRandomArrayResponse(_08_B_WebServiceClient.MyWebServiceReference.GetRandomArrayResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRandomArrayResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public _08_B_WebServiceClient.MyWebServiceReference.ArrayOfDouble GetRandomArrayResult;
        
        public GetRandomArrayResponseBody() {
        }
        
        public GetRandomArrayResponseBody(_08_B_WebServiceClient.MyWebServiceReference.ArrayOfDouble GetRandomArrayResult) {
            this.GetRandomArrayResult = GetRandomArrayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResult", Namespace="http://tempuri.org/", Order=0)]
        public _08_B_WebServiceClient.MyWebServiceReference.GetResultRequestBody Body;
        
        public GetResultRequest() {
        }
        
        public GetResultRequest(_08_B_WebServiceClient.MyWebServiceReference.GetResultRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetResultRequestBody {
        
        public GetResultRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResultResponse", Namespace="http://tempuri.org/", Order=0)]
        public _08_B_WebServiceClient.MyWebServiceReference.GetResultResponseBody Body;
        
        public GetResultResponse() {
        }
        
        public GetResultResponse(_08_B_WebServiceClient.MyWebServiceReference.GetResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public _08_B_WebServiceClient.MyWebServiceReference.ResultClass GetResultResult;
        
        public GetResultResponseBody() {
        }
        
        public GetResultResponseBody(_08_B_WebServiceClient.MyWebServiceReference.ResultClass GetResultResult) {
            this.GetResultResult = GetResultResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResult2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResult2", Namespace="http://tempuri.org/", Order=0)]
        public _08_B_WebServiceClient.MyWebServiceReference.GetResult2RequestBody Body;
        
        public GetResult2Request() {
        }
        
        public GetResult2Request(_08_B_WebServiceClient.MyWebServiceReference.GetResult2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetResult2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public _08_B_WebServiceClient.MyWebServiceReference.DataClass data;
        
        public GetResult2RequestBody() {
        }
        
        public GetResult2RequestBody(_08_B_WebServiceClient.MyWebServiceReference.DataClass data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResult2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResult2Response", Namespace="http://tempuri.org/", Order=0)]
        public _08_B_WebServiceClient.MyWebServiceReference.GetResult2ResponseBody Body;
        
        public GetResult2Response() {
        }
        
        public GetResult2Response(_08_B_WebServiceClient.MyWebServiceReference.GetResult2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetResult2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public _08_B_WebServiceClient.MyWebServiceReference.ResultClass GetResult2Result;
        
        public GetResult2ResponseBody() {
        }
        
        public GetResult2ResponseBody(_08_B_WebServiceClient.MyWebServiceReference.ResultClass GetResult2Result) {
            this.GetResult2Result = GetResult2Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyWebServiceSoapChannel : _08_B_WebServiceClient.MyWebServiceReference.MyWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyWebServiceSoapClient : System.ServiceModel.ClientBase<_08_B_WebServiceClient.MyWebServiceReference.MyWebServiceSoap>, _08_B_WebServiceClient.MyWebServiceReference.MyWebServiceSoap {
        
        public MyWebServiceSoapClient() {
        }
        
        public MyWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _08_B_WebServiceClient.MyWebServiceReference.HelloWorldResponse _08_B_WebServiceClient.MyWebServiceReference.MyWebServiceSoap.HelloWorld(_08_B_WebServiceClient.MyWebServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            _08_B_WebServiceClient.MyWebServiceReference.HelloWorldRequest inValue = new _08_B_WebServiceClient.MyWebServiceReference.HelloWorldRequest();
            inValue.Body = new _08_B_WebServiceClient.MyWebServiceReference.HelloWorldRequestBody();
            _08_B_WebServiceClient.MyWebServiceReference.HelloWorldResponse retVal = ((_08_B_WebServiceClient.MyWebServiceReference.MyWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_08_B_WebServiceClient.MyWebServiceReference.HelloWorldResponse> _08_B_WebServiceClient.MyWebServiceReference.MyWebServiceSoap.HelloWorldAsync(_08_B_WebServiceClient.MyWebServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<_08_B_WebServiceClient.MyWebServiceReference.HelloWorldResponse> HelloWorldAsync() {
            _08_B_WebServiceClient.MyWebServiceReference.HelloWorldRequest inValue = new _08_B_WebServiceClient.MyWebServiceReference.HelloWorldRequest();
            inValue.Body = new _08_B_WebServiceClient.MyWebServiceReference.HelloWorldRequestBody();
            return ((_08_B_WebServiceClient.MyWebServiceReference.MyWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _08_B_WebServiceClient.MyWebServiceReference.HelloWorld2Response _08_B_WebServiceClient.MyWebServiceReference.MyWebServiceSoap.HelloWorld2(_08_B_WebServiceClient.MyWebServiceReference.HelloWorld2Request request) {
            return base.Channel.HelloWorld2(request);
        }
        
        public string HelloWorld2(string name) {
            _08_B_WebServiceClient.MyWebServiceReference.HelloWorld2Request inValue = new _08_B_WebServiceClient.MyWebServiceReference.HelloWorld2Request();
            inValue.Body = new _08_B_WebServiceClient.MyWebServiceReference.HelloWorld2RequestBody();
            inValue.Body.name = name;
            _08_B_WebServiceClient.MyWebServiceReference.HelloWorld2Response retVal = ((_08_B_WebServiceClient.MyWebServiceReference.MyWebServiceSoap)(this)).HelloWorld2(inValue);
            return retVal.Body.HelloWorld2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_08_B_WebServiceClient.MyWebServiceReference.HelloWorld2Response> _08_B_WebServiceClient.MyWebServiceReference.MyWebServiceSoap.HelloWorld2Async(_08_B_WebServiceClient.MyWebServiceReference.HelloWorld2Request request) {
            return base.Channel.HelloWorld2Async(request);
        }
        
        public System.Threading.Tasks.Task<_08_B_WebServiceClient.MyWebServiceReference.HelloWorld2Response> HelloWorld2Async(string name) {
            _08_B_WebServiceClient.MyWebServiceReference.HelloWorld2Request inValue = new _08_B_WebServiceClient.MyWebServiceReference.HelloWorld2Request();
            inValue.Body = new _08_B_WebServiceClient.MyWebServiceReference.HelloWorld2RequestBody();
            inValue.Body.name = name;
            return ((_08_B_WebServiceClient.MyWebServiceReference.MyWebServiceSoap)(this)).HelloWorld2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _08_B_WebServiceClient.MyWebServiceReference.GetRandomArrayResponse _08_B_WebServiceClient.MyWebServiceReference.MyWebServiceSoap.GetRandomArray(_08_B_WebServiceClient.MyWebServiceReference.GetRandomArrayRequest request) {
            return base.Channel.GetRandomArray(request);
        }
        
        public _08_B_WebServiceClient.MyWebServiceReference.ArrayOfDouble GetRandomArray(int n) {
            _08_B_WebServiceClient.MyWebServiceReference.GetRandomArrayRequest inValue = new _08_B_WebServiceClient.MyWebServiceReference.GetRandomArrayRequest();
            inValue.Body = new _08_B_WebServiceClient.MyWebServiceReference.GetRandomArrayRequestBody();
            inValue.Body.n = n;
            _08_B_WebServiceClient.MyWebServiceReference.GetRandomArrayResponse retVal = ((_08_B_WebServiceClient.MyWebServiceReference.MyWebServiceSoap)(this)).GetRandomArray(inValue);
            return retVal.Body.GetRandomArrayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_08_B_WebServiceClient.MyWebServiceReference.GetRandomArrayResponse> _08_B_WebServiceClient.MyWebServiceReference.MyWebServiceSoap.GetRandomArrayAsync(_08_B_WebServiceClient.MyWebServiceReference.GetRandomArrayRequest request) {
            return base.Channel.GetRandomArrayAsync(request);
        }
        
        public System.Threading.Tasks.Task<_08_B_WebServiceClient.MyWebServiceReference.GetRandomArrayResponse> GetRandomArrayAsync(int n) {
            _08_B_WebServiceClient.MyWebServiceReference.GetRandomArrayRequest inValue = new _08_B_WebServiceClient.MyWebServiceReference.GetRandomArrayRequest();
            inValue.Body = new _08_B_WebServiceClient.MyWebServiceReference.GetRandomArrayRequestBody();
            inValue.Body.n = n;
            return ((_08_B_WebServiceClient.MyWebServiceReference.MyWebServiceSoap)(this)).GetRandomArrayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _08_B_WebServiceClient.MyWebServiceReference.GetResultResponse _08_B_WebServiceClient.MyWebServiceReference.MyWebServiceSoap.GetResult(_08_B_WebServiceClient.MyWebServiceReference.GetResultRequest request) {
            return base.Channel.GetResult(request);
        }
        
        public _08_B_WebServiceClient.MyWebServiceReference.ResultClass GetResult() {
            _08_B_WebServiceClient.MyWebServiceReference.GetResultRequest inValue = new _08_B_WebServiceClient.MyWebServiceReference.GetResultRequest();
            inValue.Body = new _08_B_WebServiceClient.MyWebServiceReference.GetResultRequestBody();
            _08_B_WebServiceClient.MyWebServiceReference.GetResultResponse retVal = ((_08_B_WebServiceClient.MyWebServiceReference.MyWebServiceSoap)(this)).GetResult(inValue);
            return retVal.Body.GetResultResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_08_B_WebServiceClient.MyWebServiceReference.GetResultResponse> _08_B_WebServiceClient.MyWebServiceReference.MyWebServiceSoap.GetResultAsync(_08_B_WebServiceClient.MyWebServiceReference.GetResultRequest request) {
            return base.Channel.GetResultAsync(request);
        }
        
        public System.Threading.Tasks.Task<_08_B_WebServiceClient.MyWebServiceReference.GetResultResponse> GetResultAsync() {
            _08_B_WebServiceClient.MyWebServiceReference.GetResultRequest inValue = new _08_B_WebServiceClient.MyWebServiceReference.GetResultRequest();
            inValue.Body = new _08_B_WebServiceClient.MyWebServiceReference.GetResultRequestBody();
            return ((_08_B_WebServiceClient.MyWebServiceReference.MyWebServiceSoap)(this)).GetResultAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _08_B_WebServiceClient.MyWebServiceReference.GetResult2Response _08_B_WebServiceClient.MyWebServiceReference.MyWebServiceSoap.GetResult2(_08_B_WebServiceClient.MyWebServiceReference.GetResult2Request request) {
            return base.Channel.GetResult2(request);
        }
        
        public _08_B_WebServiceClient.MyWebServiceReference.ResultClass GetResult2(_08_B_WebServiceClient.MyWebServiceReference.DataClass data) {
            _08_B_WebServiceClient.MyWebServiceReference.GetResult2Request inValue = new _08_B_WebServiceClient.MyWebServiceReference.GetResult2Request();
            inValue.Body = new _08_B_WebServiceClient.MyWebServiceReference.GetResult2RequestBody();
            inValue.Body.data = data;
            _08_B_WebServiceClient.MyWebServiceReference.GetResult2Response retVal = ((_08_B_WebServiceClient.MyWebServiceReference.MyWebServiceSoap)(this)).GetResult2(inValue);
            return retVal.Body.GetResult2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_08_B_WebServiceClient.MyWebServiceReference.GetResult2Response> _08_B_WebServiceClient.MyWebServiceReference.MyWebServiceSoap.GetResult2Async(_08_B_WebServiceClient.MyWebServiceReference.GetResult2Request request) {
            return base.Channel.GetResult2Async(request);
        }
        
        public System.Threading.Tasks.Task<_08_B_WebServiceClient.MyWebServiceReference.GetResult2Response> GetResult2Async(_08_B_WebServiceClient.MyWebServiceReference.DataClass data) {
            _08_B_WebServiceClient.MyWebServiceReference.GetResult2Request inValue = new _08_B_WebServiceClient.MyWebServiceReference.GetResult2Request();
            inValue.Body = new _08_B_WebServiceClient.MyWebServiceReference.GetResult2RequestBody();
            inValue.Body.data = data;
            return ((_08_B_WebServiceClient.MyWebServiceReference.MyWebServiceSoap)(this)).GetResult2Async(inValue);
        }
    }
}
